backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "sections"
    label: "Sections"
    files:
      - label: "Introduction"
        name: "introduction"
        file: "src/sections/intro.md"
        fields:
          - {label: Introduction, name: body, widget: markdown}
          - {label: Hugh, name: hugh, widget: text}
