backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - file: "src/pages/index.md"
        name: homepage
        label: Homepage
        fields:
          - label: Page identier
            name: pageIdentifier
            widget: hidden
          - label: Template key
            name: templateKey
            widget: hidden
          - label: "Introduction"
            name: "introduction"
            widget: object
            fields:
              - {label: Text, name: introText, widget: markdown}
              - {label: Opening dates, name: openingDatesText, widget: string}

          - label: Divider Image
            name: divider1
            widget: image

          - label: "Rooms"
            name: "rooms"
            widget: object
            fields:
              - label: Title
                name: title
                widget: string
              - label:  Text
                name: intro1
                widget: markdown
                required: false
              - label: Text
                name: intro2
                widget: markdown
                required: false
              - label: 'Room information'
                allow_add: false
                name: roomInfo
                widget: list
                fields:
                  - {label: 'Room name', name: roomName, widget: string}
                  - {label: Image, name: roomImage, widget: image}
                  - label: 'Room highlights'
                    name: roomHighlights
                    widget: list
                    field: {label: Highlight, name: highlight, widget: string}
                  - {label: Price, name: price, widget: string}
                  - {label: Single occupancy text, name: soText, widget: string, required: false}

          - label: "Food & Drink"
            name: foodAndDrink
            widget: object
            fields:
              - {label: Title, name: title, widget: string }
              - {label: Text, name: openingText, widget: markdown }
              - {label: Image, name: foodImage1, widget: image }
              - {label: Text, name: dividerText1, widget: markdown }
              - {label: Image, name: foodImage2, widget: image }
              - {label: Text, name: dividerText2, widget: markdown }
              - {label: Image, name: foodImage3, widget: image }
              - label: 'Menu items'
                name: menuItems
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Description, name: description, widget: string, required: false}

          - label: Experiences
            name: experiences
            widget: object
            fields:
              - {label: Title, name: title, widget: string }
              - {label: Text, name: openingText, widget: markdown }
              - {label: Image, name: dividerExperiences, widget: image }
              - {label: Text, name: secondaryText, widget: markdown }

          - label: About Us
            name: aboutUs
            widget: object
            fields:
              - {label: Title, name: title, widget: string }
              - {label: Text, name: aboutUsText, widget: markdown }
              - {label: Title, name: title2, widget: string }
              - {label: Text, name: aboutUsText2, widget: markdown }