backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# when using the default proxy server port
local_backend: false

media_folder: static/img
public_folder: /img
editor:
  preview: false
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - file: 'src/pages/index.md'
        name: homepage
        label: Homepage
        editor:
          preview: false
        fields:
          - label: Page identier
            name: pageIdentifier
            widget: hidden

          - label: Template key
            name: templateKey
            widget: hidden

          - label: Splash image
            name: splashImage
            widget: image

          - label: Alert message
            collapsed: true
            name: alert
            widget: object
            fields:
              - label: Show alert
                name: showAlert
                widget: boolean
                hint: Toggle whether the alert is shown or not
                required: false
              - label: Title
                name: alertTitle
                required: false
                widget: string
              - label: Alert text
                name: alertText
                required: false
                widget: text

          - label: Introduction
            name: introduction
            widget: object
            collapsed: true
            fields:
              - label: Text
                name: introText
                widget: markdown
                buttons: ['bulleted-list', 'numbered-list']
                editorComponents: []
              - label: Opening dates
                name: openingDatesText
                widget: string

          - label: Divider Image
            name: divider1
            widget: image

          - label: 'Rooms'
            name: 'rooms'
            widget: object
            collapsed: true
            fields:
              - label: Title
                name: title
                widget: string
              - label: Text
                name: intro1
                widget: markdown
                required: false
                buttons: ['bulleted-list', 'numbered-list']
                editorComponents: []
              - label: Sub title
                name: intro2subtitle
                required: false
                widget: string
              - label: Text
                name: intro2
                widget: markdown
                required: false
                buttons: ['bulleted-list', 'numbered-list']
                editorComponents: []
              - label: Sub title
                name: intro3subtitle
                required: false
                widget: string
              - label: Text
                name: intro3
                widget: markdown
                required: false
                buttons: ['bulleted-list', 'numbered-list']
                editorComponents: []
              - label: 'Room information'
                allow_add: false
                name: roomInfo
                widget: list
                fields:
                  - label: 'Room name'
                    name: roomName
                    widget: string

                  - label: Images
                    name: roomImages
                    widget: list
                    fields:
                      - label: Image
                        name: roomImage
                        widget: image

                      - label: Alt text
                        required: false
                        name: roomImageAlt
                        widget: string
                        hint: provide some descriptive text for this image

                  - label: 'Room highlights'
                    name: roomHighlights
                    widget: list
                    field: { label: Highlight, name: highlight, widget: string }
                  - { label: Price, name: price, widget: string }
                  - {
                      label: Single occupancy text,
                      name: soText,
                      widget: string,
                      required: false,
                    }

          - label: 'Food & Drink'
            name: foodAndDrink
            widget: object
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - {
                  label: Text,
                  name: openingText,
                  widget: markdown,
                  buttons: ['bulleted-list', 'numbered-list'],
                  editorComponents: [],
                }
              - { label: Image, name: foodImage1, widget: image }
              - {
                  label: Text,
                  name: dividerText1,
                  widget: markdown,
                  buttons: ['bulleted-list', 'numbered-list'],
                  editorComponents: [],
                }
              - { label: Image, name: foodImage2, widget: image }
              - {
                  label: Text,
                  name: dividerText2,
                  widget: markdown,
                  buttons: ['bulleted-list', 'numbered-list'],
                  editorComponents: [],
                }
              - { label: Image, name: foodImage3, widget: image }
              - label: 'Menu items'
                name: menuItems
                widget: list
                fields:
                  - { label: Title, name: title, widget: string }
                  - {
                      label: Description,
                      name: description,
                      widget: string,
                      required: false,
                    }

          - label: Experiences
            name: experiences
            widget: object
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - {
                  label: Text,
                  name: openingText,
                  widget,
                  buttons: ['bulleted-list', 'numbered-list'],
                }
              - { label: Image, name: dividerExperiences, widget: image }
              - {
                  label: Text,
                  name: secondaryText,
                  widget: markdown,
                  buttons: ['bulleted-list', 'numbered-list'],
                  editorComponents: [],
                }

          - label: Gallery Images
            name: gallery
            hint: All images should be the same width and height (2880x1200px)
            widget: list
            fields:
              - { label: Image, name: galleryImage, widget: image }
              - {
                  label: Alt text,
                  name: altText,
                  widget: text,
                  required: false,
                  hint: Provide some description text of the image,
                }

          - label: About Us
            name: aboutUs
            widget: object
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - {
                  label: Text,
                  name: aboutUsText,
                  widget: markdown,
                  buttons: ['bulleted-list', 'numbered-list'],
                  editorComponents: [],
                }
              - { label: Profile image, name: profileImage, widget: image }
              - { label: Title, name: title2, widget: string }
              - {
                  label: Text,
                  name: aboutUsText2,
                  widget: markdown,
                  buttons: ['bulleted-list', 'numbered-list'],
                  editorComponents: [],
                }

          - label: Footer
            name: footer,
            widget: object
            collapsed: true
            fields:
              - label: Award images
                name: awardImages
                widget: list
                fields:
                  - { label: Image, name: awardImage, widget: image }
