backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    file: "src/pages/index.md"
    fields:
      - label: "Introduction"
        name: "introduction"
        widget: object
        fields:
          - {label: Introduction, name: introduction, widget: markdown}

      - label: "Rooms"
        name: "rooms"
        widget: object
        fields:
          - label: Title
            name: title
            widget: string
          - label: Introductory text
            name: intro1
            widget: markdown
          - label: Introductory text
            name: intro2
            widget: markdown
          - label: 'Room information'
            allow_add: false
            name: roomInfo
            widget: list
            fields:
              - {label: 'Room name', name: roomName, widget: string}
              - {label: Image, name: roomImage, widget: image}
              - label: 'Room highlights'
                name: roomHighlights
                widget: list
                field: {label: Highlight, name: highlight, widget: string}
              - {label: Price, name: price, widget: string}
              - {label: Single Occupancy, name: soText, widget: string}

      - label: "Food & Drink"
        name: foodAndDrink
        widget: object
        fields:
          - {label: Title, name: title, widget: string }
          - {label: Text, name: openingText, widget: markdown }
          - {label: Text, name: dividerText1, widget: markdown }
          - {label: Text, name: dividerText2, widget: markdown }
          - label: 'Menu items'
            name: menuItems
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}

      - label: Experiences
        name: experiences
        widget: object
        fields:
          - {label: Title, name: title, widget: string }
          - {label: Text, name: openingText, widget: markdown }
          - {label: Text, name: secondaryText, widget: markdown }


  - label: "Sections"
    name: "sections"
    files:
      - label: "Introduction"
        name: "introduction"
        file: "src/sections/intro.md"
        fields:
          - {label: Introduction, name: body, widget: markdown}

      - label: "Rooms"
        name: "rooms"
        file: "src/sections/rooms.md"
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
          - label: 'Room information'
            allow_add: false
            name: roomInfo
            widget: list
            fields:
              - {label: 'Room name', name: roomName, widget: string}
              - {label: Image, name: roomImage, widget: image}
              - label: 'Room highlights'
                name: roomHighlights
                widget: list
                field: {label: Highlight, name: highlight, widget: string}
              - {label: Price, name: price, widget: string}
              - {label: Single Occupancy, name: soText, widget: string}

      - label: "Food & Drink"
        name: "foodanddrink"
        file: "src/sections/foodanddrink.md"
        fields:
          - {label: Title, name: title, widget: string }
          - {label: Opening text, name: openingText, widget: text }
          - {label: Divider text 1, name: dividerText1, widget: text }
          - {label: Divider text 2, name: dividerText2, widget: text }
          - label: 'Menu items'
            name: menuItems
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}

      - label: "Experiences"
        name: "experiences"
        file: "src/sections/experiences.md"
        fields:
          - {label: Title, name: title, widget: string }
          - {label: Opening text, name: openingText, widget: text }
          - {label: Secondary text, name: body, widget: markdown }
