backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "Introduction"
        name: "introduction"
        file: "src/sections/intro.md"
        fields:
          - {label: Introduction, name: body, widget: markdown}

      - label: "Rooms"
        name: "rooms"
        file: "src/sections/rooms.md"
        fields:
          - {label: Title, name: title, widget: string }
          - {label: Body, name: body, widget: markdown }

      - label: "Food & Drink"
        name: "foodanddrink"
        file: "src/sections/foodanddrink.md"
        fields:
          - {label: Title, name: title, widget: string }
          - {label: Opening text, name: openingText, widget: text }
          - {label: Divider text 1, name: dividerText1, widget: text }
          - {label: Divider text 2, name: dividerText2, widget: text }

      - label: "Experiences"
        name: "experiences"
        file: "src/sections/experiences.md"
        fields:
          - {label: Title, name: title, widget: string }
          - {label: Opening text, name: openingText, widget: text }
          - {label: Secondary text, name: body, widget: markdown }
